# Numpy

In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)

[[1 2 3]
 [2 3 4]]


## 几种属性 

In [4]:
print('number of dim:',array.ndim)  # 维度

number of dim: 2


In [5]:
print('shape :',array.shape)    # 行数和列数

shape : (2, 3)


In [6]:
print('size:',array.size)   # 元素个数

size: 6


## 创建 array

### 创建数组

In [7]:
a = np.array([2,23,4])  # list 1d
print(a)

[ 2 23  4]


### 指定数据 dtype

In [11]:
a = np.array([2,23,4],dtype=np.int64)
print(a.dtype)

int64


In [12]:
a = np.array([2,23,4],dtype=np.int)
print(a.dtype)

int32


In [10]:
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)

int32


In [14]:
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)

float64


In [15]:
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)

float32


### 创建特定数据

In [16]:
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [18]:
a = np.zeros((3,4)) # 数据全为0，3行4列
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [21]:
a = np.empty((3,4)) # 数据为empty，3行4列,创建全空数组, 其实每个值都是接近于零的数
print(a)

[[1.16140351e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.70496658e-056 1.65530290e-047 1.60268515e-051]
 [5.24632186e+174 3.34258643e-061 4.43201281e+175 3.98263844e-062]]


In [22]:
a = np.arange(10,20,2) # 10-19 的数据，2步长,用 arange 创建连续数组
print(a)

[10 12 14 16 18]


In [23]:
a = np.arange(12).reshape((3,4))    # 3行4列，0到11,使用 reshape 改变数据的形状
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
a = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段,用 linspace 创建线段型数据
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [25]:
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
print(a)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


## 基础运算

In [26]:
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)              # array([0, 1, 2, 3])

In [27]:
c=a-b  # array([10, 19, 28, 37])

In [28]:
c=a*b   # array([  0,  20,  60, 120])

#### 想要求出矩阵中各个元素的乘方需要依赖双星符号

In [29]:
c=b**2  # array([0, 1, 4, 9])

In [30]:
c=10*np.sin(a)  
# array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])
#具有很多的数学函数工具

In [31]:
print(b<3)  
# array([ True,  True,  True, False], dtype=bool)
#脚本中对print函数进行一些修改可以进行逻辑判断

[ True  True  True False]


#### 脚本中对print函数进行一些修改可以进行逻辑判断

#### 上述运算均是建立在一维矩阵，即只有一行的矩阵上面的计算

### 对多行多维度的矩阵进行操作

In [32]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))

print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


#### Numpy中的矩阵乘法分为两种， 其一是前文中的对应元素相乘，其二是标准的矩阵乘法运算

In [33]:
c_dot = np.dot(a,b)
print(c_dot)

[[2 4]
 [2 3]]


In [34]:
c_dot_2 = a.dot(b)
print(c_dot_2)

[[2 4]
 [2 3]]


In [35]:
a=np.random.random((2,4))
print(a)

[[0.09753915 0.67923745 0.59660795 0.78114186]
 [0.85640744 0.16174155 0.3097723  0.28189028]]


In [36]:
print(np.sum(a))

3.7643379818573233


In [37]:
print(np.min(a))

0.09753914869156766


In [39]:
print(np.max(a))

0.8564074374433918


### 如果你需要对行或者列进行查找运算，就需要在上述代码中为 axis 进行赋值。

### 当axis的值为0的时候，将会以列作为查找单元， 当axis的值为1的时候，将会以行作为查找单元

In [40]:
print("sum =",np.sum(a,axis=1))

sum = [2.15452641 1.60981157]


In [41]:
print("min =",np.min(a,axis=0))

min = [0.09753915 0.16174155 0.3097723  0.28189028]


In [42]:
print("max =",np.max(a,axis=1))

max = [0.78114186 0.85640744]


### argmin() 和 argmax() 两个函数分别对应着求矩阵中最小元素和最大元素的索引

In [44]:
import numpy as np
A = np.arange(2,14).reshape((3,4)) 
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [45]:
print(np.argmin(A))    
print(np.argmax(A))   

0
11


In [47]:
print(np.mean(A))        
print(np.average(A))
print(A.mean()) 

7.5
7.5
7.5


In [51]:
print(np.median(A))

7.5


In [52]:
print(np.cumsum(A)) #)累加函数

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [53]:
print(np.diff(A)) #累差运算函数,每一行中后一项与前一项之差

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [55]:
A = np.arange(14,2, -1).reshape((3,4)) 
print(A)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [56]:
print(np.sort(A))   

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


### 矩阵的转置有两种表示方法

In [57]:
print(np.transpose(A))    
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [58]:
print(np.clip(A,5,9))   

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


#### clip(Array,Array_min,Array_max) 

判断矩阵中元素是否有比最小值小的或者比最大值大的元素，并将这些指定的元素转换为最小值或者最大值

## 索引

In [59]:
A = np.arange(3,15)

# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
         
print(A[3])    # 6

6


In [60]:
A = np.arange(3,15).reshape((3,4))
"""
array([[ 3,  4,  5,  6]
       [ 7,  8,  9, 10]
       [11, 12, 13, 14]])
"""
         
print(A[2])         
# [11 12 13 14]

[11 12 13 14]


In [61]:
print(A[1][1])      # 8
print(A[1, 1])      # 8
print(A[1, 1:3])    # [8 9]

8
8
[8 9]


In [62]:
print(A.flatten())   #展开

[ 3  4  5  6  7  8  9 10 11 12 13 14]


### 合并

In [63]:
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B)))    # vertical stack

[[1 1 1]
 [2 2 2]]


In [64]:
D = np.hstack((A,B))
print(D)

[1 1 1 2 2 2]


### np.newaxis()

如果面对如同前文所述的A序列， 转置操作便很有可能无法对其进行转置（因为A并不是矩阵的属性），此时就需要我们借助其他的函数操作进行转置

In [6]:
import numpy as np
A = np.array([1,1,1])
print(A)
print(A.shape)
print(A[np.newaxis,:])
print(A[np.newaxis,:].shape)

[1 1 1]
(3,)
[[1 1 1]]
(1, 3)


In [10]:
print(A[:,np.newaxis])
print(A[:,np.newaxis].shape)

[[1]
 [1]
 [1]]
(3, 1)


### np.concatenate()  An easy way!

In [12]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print(A)
print(B)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


In [13]:
C = np.concatenate((A,B,B,A),axis=0)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [14]:
D = np.concatenate((A,B,B,A),axis=1)
print(D)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


### axis参数很好的控制了矩阵的纵向或是横向打印，相比较vstack和hstack函数显得更加方便。

## 分割

In [15]:
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
print(np.split(A, 2, axis=1)) #纵向分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [17]:
print(np.split(A, 3, axis=0)) #横向分割

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


### 不等量的分割

In [18]:
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


### Numpy copy & deep copy

#### "="会带来关联性，会同时指向同一块内存

### copy() 的赋值方式没有关联性

In [19]:
a=np.array([1,2,3,4])
b = a.copy()    # deep copy
print(b)    
a[3] = 44
print(a)        
print(b)        

[1 2 3 4]
[ 1  2  3 44]
[1 2 3 4]
